"""baseline schema

Revision ID: 0f0766accf80
Revises: 
Create Date: 2026-06-18 18:53:46.942728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f0766accf80'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expense_items', 'attributes_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               schema='trackspense')
    op.drop_index('idx_expense_items_expense_id', table_name='expense_items', schema='trackspense')
    op.create_index(op.f('ix_trackspense_expense_items_expense_id'), 'expense_items', ['expense_id'], unique=False, schema='trackspense')
    op.drop_index('idx_expenses_purchased_at', table_name='expenses', schema='trackspense')
    op.drop_index('idx_expenses_user_email', table_name='expenses', schema='trackspense')
    op.create_index(op.f('ix_trackspense_expenses_purchased_at'), 'expenses', ['purchased_at'], unique=False, schema='trackspense')
    op.create_index(op.f('ix_trackspense_expenses_user_email'), 'expenses', ['user_email'], unique=False, schema='trackspense')
    op.drop_index('idx_recurring_templates_user_email', table_name='recurring_templates', schema='trackspense')
    op.create_index(op.f('ix_trackspense_recurring_templates_user_email'), 'recurring_templates', ['user_email'], unique=False, schema='trackspense')
    op.drop_constraint('users_email_key', 'users', schema='trackspense', type_='unique')
    op.create_index(op.f('ix_trackspense_users_email'), 'users', ['email'], unique=True, schema='trackspense')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trackspense_users_email'), table_name='users', schema='trackspense')
    op.create_unique_constraint('users_email_key', 'users', ['email'], schema='trackspense', postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_trackspense_recurring_templates_user_email'), table_name='recurring_templates', schema='trackspense')
    op.create_index('idx_recurring_templates_user_email', 'recurring_templates', ['user_email'], unique=False, schema='trackspense')
    op.drop_index(op.f('ix_trackspense_expenses_user_email'), table_name='expenses', schema='trackspense')
    op.drop_index(op.f('ix_trackspense_expenses_purchased_at'), table_name='expenses', schema='trackspense')
    op.create_index('idx_expenses_user_email', 'expenses', ['user_email'], unique=False, schema='trackspense')
    op.create_index('idx_expenses_purchased_at', 'expenses', ['purchased_at'], unique=False, schema='trackspense')
    op.drop_index(op.f('ix_trackspense_expense_items_expense_id'), table_name='expense_items', schema='trackspense')
    op.create_index('idx_expense_items_expense_id', 'expense_items', ['expense_id'], unique=False, schema='trackspense')
    op.alter_column('expense_items', 'attributes_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               schema='trackspense')
    # ### end Alembic commands ###
