"""add expense_item_splits

Revision ID: b221e1af9b3d
Revises: fdb24441b181
Create Date: 2026-07-07 07:20:55.908485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b221e1af9b3d'
down_revision: Union[str, None] = 'fdb24441b181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_item_splits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('expense_item_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('ratio', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['expense_item_id'], ['trackspense.expense_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['trackspense.group_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('expense_item_id', 'member_id', name='uq_expense_item_splits_item_member'),
    schema='trackspense'
    )
    op.create_index(op.f('ix_trackspense_expense_item_splits_member_id'), 'expense_item_splits', ['member_id'], unique=False, schema='trackspense')
    # op.drop_constraint('users_email_key', 'users', schema='trackspense', type_='unique')
    # op.create_index(op.f('ix_trackspense_users_email'), 'users', ['email'], unique=True, schema='trackspense')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_trackspense_users_email'), table_name='users', schema='trackspense')
    # op.create_unique_constraint('users_email_key', 'users', ['email'], schema='trackspense', postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_trackspense_expense_item_splits_member_id'), table_name='expense_item_splits', schema='trackspense')
    op.drop_table('expense_item_splits', schema='trackspense')
    # ### end Alembic commands ###
