"""add address to users

Revision ID: bb6805ddfcad
Revises: 0f0766accf80
Create Date: 2026-06-18 18:54:55.765371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb6805ddfcad'
down_revision: Union[str, None] = '0f0766accf80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.String(length=500), nullable=True), schema='trackspense')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'address', schema='trackspense')
    # ### end Alembic commands ###
