"""insights canonical fk columns

Revision ID: c0cf6118cdec
Revises: d5f5cfe66abe
Create Date: 2026-07-17 09:10:00.000000

TS-ANL-201 (partial — dual-write columns only, cutover is a later change):
item_insights.canonical_item_id / merchant_insights.canonical_merchant_id.
Hand-written, NOT autogenerated. item_insights/merchant_insights predate
Alembic (created via Base.metadata.create_all(), never CREATE TABLE'd by any
prior revision) — autogenerate would try to re-issue CREATE TABLE for both.
Verified against the live dev DB (`\\d trackspense.item_insights` /
`\\d trackspense.merchant_insights`) before writing this: neither column
exists yet, so this is purely additive.

Nullable, no default — these are populated going forward by the dual-write
change to InsightsAggregationService (separate PR), then backfilled for
pre-existing rows by a one-off script (not a migration, since it's a data
transform, not a schema change). No read path switches to these columns yet.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'c0cf6118cdec'
down_revision: Union[str, None] = 'd5f5cfe66abe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'item_insights',
        sa.Column('canonical_item_id', postgresql.UUID(as_uuid=True), nullable=True),
        schema='trackspense',
    )
    op.create_foreign_key(
        'fk_item_insights_canon_item', 'item_insights', 'canonical_items',
        ['canonical_item_id'], ['id'], source_schema='trackspense', referent_schema='trackspense',
        ondelete='CASCADE',
    )
    op.create_index(
        op.f('ix_trackspense_item_insights_canonical_item_id'),
        'item_insights', ['canonical_item_id'], unique=False, schema='trackspense',
    )

    op.add_column(
        'merchant_insights',
        sa.Column('canonical_merchant_id', postgresql.UUID(as_uuid=True), nullable=True),
        schema='trackspense',
    )
    op.create_foreign_key(
        'fk_merchant_insights_canon_merchant', 'merchant_insights', 'canonical_merchants',
        ['canonical_merchant_id'], ['id'], source_schema='trackspense', referent_schema='trackspense',
        ondelete='CASCADE',
    )
    op.create_index(
        op.f('ix_trackspense_merchant_insights_canonical_merchant_id'),
        'merchant_insights', ['canonical_merchant_id'], unique=False, schema='trackspense',
    )


def downgrade() -> None:
    op.drop_index(
        op.f('ix_trackspense_merchant_insights_canonical_merchant_id'),
        table_name='merchant_insights', schema='trackspense',
    )
    op.drop_constraint('fk_merchant_insights_canon_merchant', 'merchant_insights', schema='trackspense', type_='foreignkey')
    op.drop_column('merchant_insights', 'canonical_merchant_id', schema='trackspense')

    op.drop_index(
        op.f('ix_trackspense_item_insights_canonical_item_id'),
        table_name='item_insights', schema='trackspense',
    )
    op.drop_constraint('fk_item_insights_canon_item', 'item_insights', schema='trackspense', type_='foreignkey')
    op.drop_column('item_insights', 'canonical_item_id', schema='trackspense')
