"""entity resolution canonical tables

Revision ID: c5c9d0accc5a
Revises: 1e2c54195f60
Create Date: 2026-07-17 09:00:00.000000

TS-ENT-101: canonical_merchants, canonical_items, entity_aliases + pg_trgm.
Hand-written (not autogenerated) — see docs/features/smart_entity plan notes:
autogenerate can't detect extensions or GIN opclasses, and these three tables
are brand new so there's no drift risk to reconcile against.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'c5c9d0accc5a'
down_revision: Union[str, None] = '1e2c54195f60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')

    op.create_table(
        'canonical_merchants',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_email', sa.String(length=255), nullable=True),
        sa.Column('canonical_name', sa.String(length=255), nullable=False),
        sa.Column('display_name', sa.String(length=255), nullable=False),
        sa.Column('default_category_id', sa.String(length=100), nullable=True),
        sa.Column('is_global', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_email'], ['trackspense.users.email'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        schema='trackspense',
    )
    op.create_index(
        op.f('ix_trackspense_canonical_merchants_user_email'),
        'canonical_merchants', ['user_email'], unique=False, schema='trackspense',
    )
    op.create_index(
        'idx_canon_merchants_trgm', 'canonical_merchants', ['canonical_name'],
        unique=False, schema='trackspense', postgresql_using='gin',
        postgresql_ops={'canonical_name': 'gin_trgm_ops'},
    )

    op.create_table(
        'canonical_items',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_email', sa.String(length=255), nullable=True),
        sa.Column('canonical_name', sa.String(length=255), nullable=False),
        sa.Column('display_name', sa.String(length=255), nullable=False),
        sa.Column('brand', sa.String(length=255), nullable=True),
        sa.Column('default_category_id', sa.String(length=100), nullable=True),
        sa.Column('unit_type', sa.String(length=50), nullable=True),
        sa.Column('is_global', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_email'], ['trackspense.users.email'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        schema='trackspense',
    )
    op.create_index(
        op.f('ix_trackspense_canonical_items_user_email'),
        'canonical_items', ['user_email'], unique=False, schema='trackspense',
    )
    op.create_index(
        'idx_canon_items_trgm', 'canonical_items', ['canonical_name'],
        unique=False, schema='trackspense', postgresql_using='gin',
        postgresql_ops={'canonical_name': 'gin_trgm_ops'},
    )

    op.create_table(
        'entity_aliases',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_email', sa.String(length=255), nullable=True),
        sa.Column('entity_type', sa.String(length=20), nullable=False),
        sa.Column('entity_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('raw_key', sa.String(length=255), nullable=False),
        sa.Column('source', sa.String(length=30), nullable=False),
        sa.Column('confidence', sa.Numeric(4, 3), nullable=True),
        sa.Column('confirmed', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_email'], ['trackspense.users.email'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_email', 'entity_type', 'raw_key', name='uq_entity_aliases_user_type_rawkey'),
        schema='trackspense',
    )
    op.create_index(
        op.f('ix_trackspense_entity_aliases_user_email'),
        'entity_aliases', ['user_email'], unique=False, schema='trackspense',
    )
    op.create_index(
        'idx_aliases_lookup', 'entity_aliases', ['user_email', 'entity_type', 'raw_key'],
        unique=False, schema='trackspense',
    )
    op.create_index(
        'idx_aliases_rawkey_trgm', 'entity_aliases', ['raw_key'],
        unique=False, schema='trackspense', postgresql_using='gin',
        postgresql_ops={'raw_key': 'gin_trgm_ops'},
    )


def downgrade() -> None:
    op.drop_index('idx_aliases_rawkey_trgm', table_name='entity_aliases', schema='trackspense')
    op.drop_index('idx_aliases_lookup', table_name='entity_aliases', schema='trackspense')
    op.drop_index(op.f('ix_trackspense_entity_aliases_user_email'), table_name='entity_aliases', schema='trackspense')
    op.drop_table('entity_aliases', schema='trackspense')

    op.drop_index('idx_canon_items_trgm', table_name='canonical_items', schema='trackspense')
    op.drop_index(op.f('ix_trackspense_canonical_items_user_email'), table_name='canonical_items', schema='trackspense')
    op.drop_table('canonical_items', schema='trackspense')

    op.drop_index('idx_canon_merchants_trgm', table_name='canonical_merchants', schema='trackspense')
    op.drop_index(op.f('ix_trackspense_canonical_merchants_user_email'), table_name='canonical_merchants', schema='trackspense')
    op.drop_table('canonical_merchants', schema='trackspense')

    # Deliberately not dropping the pg_trgm extension — other objects/future
    # migrations may depend on it, and CREATE EXTENSION IF NOT EXISTS is cheap
    # to leave in place; dropping extensions on downgrade is generally unsafe.
