"""Add archived_at and deleted_at to Group

Revision ID: eb058f5aab6d
Revises: efa7d37ee59c
Create Date: 2026-07-07 08:16:59.774127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb058f5aab6d'
down_revision: Union[str, None] = 'efa7d37ee59c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True), schema='trackspense')
    op.add_column('groups', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True), schema='trackspense')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'deleted_at', schema='trackspense')
    op.drop_column('groups', 'archived_at', schema='trackspense')
    # ### end Alembic commands ###
