"""add_recurring_groups

Revision ID: efa7d37ee59c
Revises: b221e1af9b3d
Create Date: 2026-07-07 07:59:10.304807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efa7d37ee59c'
down_revision: Union[str, None] = 'b221e1af9b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurring_templates', sa.Column('group_id', sa.UUID(), nullable=True), schema='trackspense')
    op.add_column('recurring_templates', sa.Column('split_config', sa.JSON(), nullable=True), schema='trackspense')
    op.create_foreign_key(None, 'recurring_templates', 'groups', ['group_id'], ['id'], source_schema='trackspense', referent_schema='trackspense', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recurring_templates', schema='trackspense', type_='foreignkey')
    op.drop_column('recurring_templates', 'split_config', schema='trackspense')
    op.drop_column('recurring_templates', 'group_id', schema='trackspense')
    # ### end Alembic commands ###
