"""groups phase 1

Revision ID: fa0f13339186
Revises: bb6805ddfcad
Create Date: 2026-07-04 17:57:27.775948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa0f13339186'
down_revision: Union[str, None] = 'bb6805ddfcad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('group_type', sa.String(length=20), nullable=False),
    sa.Column('cover', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('simplify_debts', sa.Boolean(), nullable=False),
    sa.Column('default_split_json', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['trackspense.users.email'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='trackspense'
    )
    op.create_table('group_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['trackspense.groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_email'], ['trackspense.users.email'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_email', name='uq_group_members_group_user'),
    schema='trackspense'
    )
    op.create_index(op.f('ix_trackspense_group_members_user_email'), 'group_members', ['user_email'], unique=False, schema='trackspense')
    op.create_table('expense_payers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('expense_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['trackspense.expenses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['trackspense.group_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('expense_id', 'member_id', name='uq_expense_payers_expense_member'),
    schema='trackspense'
    )
    op.create_index(op.f('ix_trackspense_expense_payers_member_id'), 'expense_payers', ['member_id'], unique=False, schema='trackspense')
    op.create_table('expense_splits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('expense_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('amount_owed', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('basis_type', sa.String(length=20), nullable=False),
    sa.Column('basis_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['expense_id'], ['trackspense.expenses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['trackspense.group_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('expense_id', 'member_id', name='uq_expense_splits_expense_member'),
    schema='trackspense'
    )
    op.create_index(op.f('ix_trackspense_expense_splits_member_id'), 'expense_splits', ['member_id'], unique=False, schema='trackspense')
    op.create_table('group_activity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('actor_member_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_member_id'], ['trackspense.group_members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['trackspense.groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trackspense'
    )
    op.create_index('idx_group_activity_group_id_created', 'group_activity', ['group_id', 'created_at'], unique=False, schema='trackspense')
    op.create_table('group_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('invited_email', sa.String(length=255), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['trackspense.groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['trackspense.group_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    schema='trackspense'
    )
    op.create_table('settlements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('from_member_id', sa.UUID(), nullable=False),
    sa.Column('to_member_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('from_member_id <> to_member_id', name='chk_settlements_from_neq_to'),
    sa.ForeignKeyConstraint(['created_by'], ['trackspense.users.email'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_member_id'], ['trackspense.group_members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['trackspense.groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_member_id'], ['trackspense.group_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trackspense'
    )
    op.create_index(op.f('ix_trackspense_settlements_group_id'), 'settlements', ['group_id'], unique=False, schema='trackspense')
    op.alter_column('expense_items', 'user_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               schema='trackspense')
    op.alter_column('expense_items', 'attributes_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               schema='trackspense')
    op.drop_index('idx_expense_items_expense_id', table_name='expense_items', schema='trackspense')
    op.create_index(op.f('ix_trackspense_expense_items_expense_id'), 'expense_items', ['expense_id'], unique=False, schema='trackspense')
    op.drop_constraint('expense_items_user_email_fkey', 'expense_items', schema='trackspense', type_='foreignkey')
    op.create_foreign_key(None, 'expense_items', 'users', ['user_email'], ['email'], source_schema='trackspense', referent_schema='trackspense', ondelete='SET NULL')
    op.add_column('expenses', sa.Column('group_id', sa.UUID(), nullable=True), schema='trackspense')
    op.add_column('expenses', sa.Column('split_type', sa.String(length=20), nullable=True), schema='trackspense')
    op.alter_column('expenses', 'user_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               schema='trackspense')
    op.drop_index('idx_expenses_purchased_at', table_name='expenses', schema='trackspense')
    op.drop_index('idx_expenses_user_email', table_name='expenses', schema='trackspense')
    op.create_index(op.f('ix_trackspense_expenses_group_id'), 'expenses', ['group_id'], unique=False, schema='trackspense')
    op.create_index(op.f('ix_trackspense_expenses_purchased_at'), 'expenses', ['purchased_at'], unique=False, schema='trackspense')
    op.create_index(op.f('ix_trackspense_expenses_user_email'), 'expenses', ['user_email'], unique=False, schema='trackspense')
    op.drop_constraint('expenses_user_email_fkey', 'expenses', schema='trackspense', type_='foreignkey')
    op.create_foreign_key(None, 'expenses', 'groups', ['group_id'], ['id'], source_schema='trackspense', referent_schema='trackspense', ondelete='SET NULL')
    op.create_foreign_key(None, 'expenses', 'users', ['user_email'], ['email'], source_schema='trackspense', referent_schema='trackspense', ondelete='SET NULL')
    op.drop_index('idx_recurring_templates_user_email', table_name='recurring_templates', schema='trackspense')
    op.create_index(op.f('ix_trackspense_recurring_templates_user_email'), 'recurring_templates', ['user_email'], unique=False, schema='trackspense')
    # op.drop_constraint('users_email_key', 'users', schema='trackspense', type_='unique')
    # op.create_index(op.f('ix_trackspense_users_email'), 'users', ['email'], unique=True, schema='trackspense')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_trackspense_users_email'), table_name='users', schema='trackspense')
    # op.create_unique_constraint('users_email_key', 'users', ['email'], schema='trackspense', postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_trackspense_recurring_templates_user_email'), table_name='recurring_templates', schema='trackspense')
    op.create_index('idx_recurring_templates_user_email', 'recurring_templates', ['user_email'], unique=False, schema='trackspense')
    op.drop_constraint(None, 'expenses', schema='trackspense', type_='foreignkey')
    op.drop_constraint(None, 'expenses', schema='trackspense', type_='foreignkey')
    op.create_foreign_key('expenses_user_email_fkey', 'expenses', 'users', ['user_email'], ['email'], source_schema='trackspense', referent_schema='trackspense', ondelete='CASCADE')
    op.drop_index(op.f('ix_trackspense_expenses_user_email'), table_name='expenses', schema='trackspense')
    op.drop_index(op.f('ix_trackspense_expenses_purchased_at'), table_name='expenses', schema='trackspense')
    op.drop_index(op.f('ix_trackspense_expenses_group_id'), table_name='expenses', schema='trackspense')
    op.create_index('idx_expenses_user_email', 'expenses', ['user_email'], unique=False, schema='trackspense')
    op.create_index('idx_expenses_purchased_at', 'expenses', ['purchased_at'], unique=False, schema='trackspense')
    op.alter_column('expenses', 'user_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               schema='trackspense')
    op.drop_column('expenses', 'split_type', schema='trackspense')
    op.drop_column('expenses', 'group_id', schema='trackspense')
    op.drop_constraint(None, 'expense_items', schema='trackspense', type_='foreignkey')
    op.create_foreign_key('expense_items_user_email_fkey', 'expense_items', 'users', ['user_email'], ['email'], source_schema='trackspense', referent_schema='trackspense', ondelete='CASCADE')
    op.drop_index(op.f('ix_trackspense_expense_items_expense_id'), table_name='expense_items', schema='trackspense')
    op.create_index('idx_expense_items_expense_id', 'expense_items', ['expense_id'], unique=False, schema='trackspense')
    op.alter_column('expense_items', 'attributes_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               schema='trackspense')
    op.alter_column('expense_items', 'user_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               schema='trackspense')
    op.drop_index(op.f('ix_trackspense_settlements_group_id'), table_name='settlements', schema='trackspense')
    op.drop_table('settlements', schema='trackspense')
    op.drop_table('group_invitations', schema='trackspense')
    op.drop_index('idx_group_activity_group_id_created', table_name='group_activity', schema='trackspense')
    op.drop_table('group_activity', schema='trackspense')
    op.drop_index(op.f('ix_trackspense_expense_splits_member_id'), table_name='expense_splits', schema='trackspense')
    op.drop_table('expense_splits', schema='trackspense')
    op.drop_index(op.f('ix_trackspense_expense_payers_member_id'), table_name='expense_payers', schema='trackspense')
    op.drop_table('expense_payers', schema='trackspense')
    op.drop_index(op.f('ix_trackspense_group_members_user_email'), table_name='group_members', schema='trackspense')
    op.drop_table('group_members', schema='trackspense')
    op.drop_table('groups', schema='trackspense')
    # ### end Alembic commands ###
