"""device tokens

Revision ID: fdb24441b181
Revises: fa0f13339186
Create Date: 2026-07-04 23:47:26.549546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdb24441b181'
down_revision: Union[str, None] = 'fa0f13339186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('expo_push_token', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=10), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_email'], ['trackspense.users.email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_email', 'expo_push_token', name='uq_device_tokens_user_token'),
    schema='trackspense'
    )
    op.create_index(op.f('ix_trackspense_device_tokens_expo_push_token'), 'device_tokens', ['expo_push_token'], unique=False, schema='trackspense')
    op.create_index(op.f('ix_trackspense_device_tokens_user_email'), 'device_tokens', ['user_email'], unique=False, schema='trackspense')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trackspense_device_tokens_user_email'), table_name='device_tokens', schema='trackspense')
    op.drop_index(op.f('ix_trackspense_device_tokens_expo_push_token'), table_name='device_tokens', schema='trackspense')
    op.drop_table('device_tokens', schema='trackspense')
    # ### end Alembic commands ###
